[% if has_frontend %]
[% if spa %]
FROM [[ node_image ]]
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE [[ frontend_port ]]
CMD ["npm", "run", "dev", "--", "--host", "--port", "[[ frontend_port ]]"]
[% else %]
FROM nginx:alpine
COPY . /usr/share/nginx/html
EXPOSE 80
[% endif %]
[% endif %]
